services:
  - type: web
    name: open-recommender-ui
    env: static
    buildCommand: yarn && yarn build
    staticPublishPath: ./packages/client/dist
    branch: main
    buildFilter:
      paths:
        - packages/client/**/*.ts
        - packages/client/**/*.tsx
        - packages/shared/**/*.ts
        - packages/cli/**/*.ts
        - packages/cli/**/*.py
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
  - type: web
    plan: free
    name: open-recommender-api
    env: node
    buildCommand: yarn && yarn build
    startCommand: cd packages/server && yarn start
    branch: main
    buildFilter:
      paths:
        - packages/server/**/*.ts
        - packages/server/**/*.py
        - packages/shared/**/*.ts
        - packages/cli/**/*.ts
        - packages/cli/**/*.py
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-recommender-db
          property: connectionString
  - type: worker
    plan: starter
    name: open-recommender-worker
    env: python
    buildCommand: yarn && pip install -r requirements.txt && yarn build
    startCommand: yarn workspace server worker
    branch: main
    buildFilter:
      paths:
        - packages/server/**/*.ts
        - packages/server/**/*.py
        - packages/cli/**/*.ts
        - packages/cli/**/*.py
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-recommender-db
          property: connectionString
databases:
  - name: open-recommender-db
    plan: free
